name: nx_play
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^2.0.0
  firebase_core: ^0.7.0
  firebase_storage: ^10.0.0
  google_sign_in: ^4.5.6
  flutter_facebook_auth: ^1.0.2+2
  # github_auth: ^0.0.4
  lottie: ^0.7.0+1
  url_launcher: ^5.5.2
  uni_links: ^0.4.0
  #pusher_beams: "^0.5.3+3"
  firebase_messaging: ^10.0.0
  font_awesome_flutter: ^8.11.0
  google_fonts: ^1.1.1
  http: ^0.12.2

  image_picker: ^0.6.7+22

  pagination_view: ^1.0.4
  faker: ^1.3.0
  timeago: ^2.0.29
  flutter_score_slider: ^1.0.0

  page_transition: ^1.1.7+5

  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  flare_flutter: ^2.0.3
  flutter_dotenv: ^2.1.0
  flushbar: ^1.10.4
  flutter_spinkit: ^4.1.2
  flutter_easyloading: ^2.2.2
  #for downloading
  path_provider: ^1.6.27
  flutter_downloader: ^1.5.2
  percent_indicator: "^2.1.7+2"
  #for business logic
  dio: ^3.0.10
  bloc: ^6.1.1
  rxdart: ^0.23.1
  page_indicator: ^0.2.0
  flutter_rating_bar: ^3.2.0+1
  catcher: ^0.4.0
  meedu_player: ^0.4.3
  #awsome_video_player: ^1.0.8+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/intro_assets/
    - assets/splash_assets/
    - assets/loading_assets/
    - assets/no_internet/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Audiowide
      fonts:
        - asset: fonts/Audiowide-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
